### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by cjnqt** [devinivy/haute-couture#31]
After updating haute-couture to 2.1.0, loading fails on line 57 of /haute/lib/index.js with message: 

```
/var/www/node_modules/haute/lib/index.js:57

TypeError: argGroups.forEach is not a function
```

It turns out argGroups is a function here

**Comment by devinivy** [comment]
This looks like a bug recently introduced into haute– for a quick fix, try pinning the haute module at v1.3.1.

**Comment by cjnqt** [comment]
I had a decorations folder, containing just one file `index.js`, which looked like this: 
```
module.exports = (server, options) => {

  return [{ type: ..., property: ..., method: ... }, { type: ..., property: ..., method: ... }]

}
```

**Comment by devinivy** [comment]
Cool, that makes perfect sense.  I have a branch with the fix and test– I just want to clean it up a little bit before publishing today or tomorrow https://github.com/devinivy/haute/tree/fix-list-as-func

**Comment by devinivy** [comment]
If you reinstall haute-couture you should get v1.3.3 of haute, which contains the fix 👍 

https://github.com/devinivy/haute/compare/v1.3.2...v1.3.3
